"use strict";
const cheerio=require("cheerio-without-node-native");
const CryptoJS=require("crypto-js");
const NAME="All-Wish",BASE="https://all-wish.me",TMDB_KEY="1865f43a0549ca50d341dd9ab8b29f49",MAP="https://id-mapping-api-malid.hf.space/api/resolve",VRF_KEY="ysJhV6U27FVIjjuk",UA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36";
const H={"User-Agent":UA,"Accept":"*/*","Accept-Language":"en-US,en;q=0.9"},AJ={...H,"X-Requested-With":"XMLHttpRequest","Referer":BASE+"/"};
async function req(url,opt={},timeout=12000){const signal=typeof AbortSignal!=="undefined"&&AbortSignal.timeout?AbortSignal.timeout(timeout):undefined;const r=await fetch(url,{...opt,headers:{...H,...(opt.headers||{})},signal,skipSizeCheck:true});if(!r||!r.ok)throw new Error(`HTTP ${r?r.status:"?"}`);return r}
async function text(url,opt={},timeout){try{return await(await req(url,opt,timeout)).text()}catch(e){console.log(`[${NAME}] ${e.message}`);return null}}
async function json(url,opt={},timeout){try{return await(await req(url,opt,timeout)).json()}catch(e){console.log(`[${NAME}] ${e.message}`);return null}}
function mediaType(t){return String(t||"tv").toLowerCase()==="movie"?"movie":"tv"}
async function tmdbId(id,type){id=String(id||"").trim();if(/^\d+$/.test(id))return+id;if(!/^tt\d+$/i.test(id))return null;const d=await json(`https://api.themoviedb.org/3/find/${encodeURIComponent(id)}?api_key=${TMDB_KEY}&external_source=imdb_id`),a=type==="movie"?d&&d.movie_results:d&&d.tv_results;return a&&a[0]&&a[0].id?+a[0].id:null}
async function tmdbInfo(id,type){const d=await json(`https://api.themoviedb.org/3/${type}/${id}?api_key=${TMDB_KEY}&append_to_response=external_ids`);if(!d)return null;return{title:type==="movie"?(d.title||d.original_title):(d.name||d.original_name),original:type==="movie"?d.original_title:d.original_name,imdb:(d.external_ids&&d.external_ids.imdb_id)||d.imdb_id||null,genres:Array.isArray(d.genres)?d.genres.map(x=>x.id):[]}}
async function malMap(imdb,s,e){return imdb?json(`${MAP}?id=${encodeURIComponent(imdb)}&s=${encodeURIComponent(s)}&e=${encodeURIComponent(e)}`):null}
async function aniTitle(mal){if(!mal)return null;const q="query($idMal:Int){Media(idMal:$idMal,type:ANIME){title{english romaji}}}";const d=await json("https://graphql.anilist.co",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query:q,variables:{idMal:+mal}})});return d&&d.data&&d.data.Media?d.data.Media.title:null}
function clean(s){return String(s||"").toLowerCase().replace(/[^a-z0-9\s]/g," ").replace(/\s+/g," ").trim()}
function uniq(a){const s=new Set(),o=[];for(const v of a){const k=clean(v);if(v&&k&&!s.has(k)){s.add(k);o.push(String(v).trim())}}return o}
async function search(titles){const out=[],seen=new Set();for(const q of uniq(titles)){const h=await text(`${BASE}/filter?keyword=${encodeURIComponent(q)}`);if(!h)continue;const $=cheerio.load(h);$("div.item").each((_,el)=>{const a=$(el).find("div.name > a").first(),title=a.text().trim(),href=a.attr("href");if(!title||!href)return;let u=href.replace(/\/ep-[\d.]+\/?$/i,"").replace(/\/+$/,"");u=/^https?:\/\//i.test(u)?u:BASE+(u.startsWith("/")?u:"/"+u);if(!seen.has(u)){seen.add(u);out.push({title,url:u,exact:uniq(titles).some(x=>clean(x)===clean(title))})}})}out.sort((a,b)=>Number(b.exact)-Number(a.exact));return out}
function b64(bytes){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")}
function vrf(id){const e=encodeURIComponent(String(id)).replace(/%21/g,"!").replace(/%27/g,"'").replace(/%28/g,"(").replace(/%29/g,")").replace(/%7E/g,"~").replace(/%2A/g,"*").replace(/%20/g,"+"),k=Array.from(VRF_KEY).map(c=>c.charCodeAt(0)),d=Array.from(e).map(c=>c.charCodeAt(0)),n=Array.from({length:256},(_,i)=>i);let a=0;for(let o=0;o<256;o++){a=(a+n[o]+k[o%k.length])%256;[n[o],n[a]]=[n[a],n[o]]}const z=[];let o=0;a=0;for(const c of d){o=(o+1)%256;a=(a+n[o])%256;[n[o],n[a]]=[n[a],n[o]];z.push((c^n[(n[o]+n[a])%256])&255)}const x=b64(z),off=[-3,3,-4,2,-2,5,4,5],y=b64(Array.from(x).map((c,i)=>(c.charCodeAt(0)+off[i%8])&255));return Array.from(y).map(c=>c>="A"&&c<="Z"?String.fromCharCode((c.charCodeAt(0)-52)%26+65):c>="a"&&c<="z"?String.fromCharCode((c.charCodeAt(0)-84)%26+97):c).join("")}
async function episodes(url){const h=await text(url);if(!h)return[];const $=cheerio.load(h),id=$("main > div.container").attr("data-id");if(!id)return[];const d=await json(`${BASE}/ajax/episode/list/${encodeURIComponent(id)}?vrf=${encodeURIComponent(vrf(id))}`,{headers:AJ},30000);if(!d||d.status!==200)return[];const e=cheerio.load(d.result||""),out=[];e("div.range > div > a").each((_,el)=>{const n=e(el),m=n.attr("data-mal");out.push({ep:parseFloat(n.attr("data-slug")||"0"),ids:n.attr("data-ids")||"",mal:m?parseInt(m,10):null,sub:n.attr("data-sub")==="1",dub:n.attr("data-dub")==="1"})});return out.filter(x=>x.ids)}
function choose(list,mal,ep){const withMal=list.filter(x=>x.mal!=null);if(mal&&withMal.length){const same=list.filter(x=>x.mal===+mal);if(!same.length)return null;return same.find(x=>x.ep===+ep)||null}return list.find(x=>x.ep===+ep)||null}
function lang(label,url){const s=`${label||""} ${url||""}`.toLowerCase();if(/english|(^|[^a-z])(en|eng)([^a-z]|$)/.test(s))return["en","English"];if(/japanese|(^|[^a-z])(ja|jp|jpn)([^a-z]|$)/.test(s))return["ja","Japanese"];if(/korean|(^|[^a-z])(ko|kr|kor)([^a-z]|$)/.test(s))return["ko","Korean"];if(/chinese|mandarin|(^|[^a-z])(zh|zho|chi)([^a-z]|$)/.test(s))return["zh","Chinese"];return null}
function subs(tracks,headers,assumeEnglish){const out=[],seen=new Set();for(const t of Array.isArray(tracks)?tracks:[]){if(!t)continue;const kind=String(t.kind||"captions").toLowerCase();if(t.kind&&kind!=="captions"&&kind!=="subtitles")continue;const u=t.file||t.url||t.src;if(!u)continue;let l=lang(t.label||t.name||t.language,u);if(!l&&assumeEnglish)l=["en","English"];if(!l)continue;const k=l[0]+"|"+u;if(seen.has(k))continue;seen.add(k);out.push({url:u,language:l[0],name:`${l[1]} [All-Wish Soft Subtitle]`,headers})}return out}
function stream(url,server,section,hard,st,headers,ctx){if(!url)return null;const dub=String(section).toLowerCase().includes("dub"),mode=dub?"DUB":hard?"HARDSUB":st.length?"SUB + Soft Subs":"SUB";return{name:`${NAME} | 1080p [${mode}] • ${server}`,title:`${ctx.title} • S${ctx.s}E${ctx.e} • ${dub?"English Dub":"Japanese"}`,url,quality:"1080p",provider:NAME,type:/\.m3u8(?:$|[?#])/i.test(url)?"m3u8":"mp4",headers,language:dub?"English":"Japanese",subtitles:st}}
async function mega(url,section,hard,ctx){const h=await text(url,{headers:{"X-Requested-With":"XMLHttpRequest","Referer":"https://megaplay.buzz/"}});if(!h)return[];const m=h.match(/data-id=["'](\d+)["']/i);if(!m)return[];const d=await json(`https://megaplay.buzz/stream/getSources?id=${encodeURIComponent(m[1])}`,{headers:{"X-Requested-With":"XMLHttpRequest","Referer":url,"Origin":"https://megaplay.buzz"}}),src=d&&d.sources&&(d.sources.file||d.sources.url);if(!src)return[];const ph={"Referer":"https://megaplay.buzz/","Origin":"https://megaplay.buzz","User-Agent":UA},st=subs(d.tracks||[],ph,String(section).toLowerCase()==="sub"),s=stream(src,"MegaPlay",section,hard,st,ph,ctx);return s?[s]:[]}
async function zen(url,section,hard,ctx){const h=await text(url,{headers:{"Referer":url}});if(!h)return[];const v=h.match(/video_b64:\s*["']([^"']+)["']/i),k=h.match(/enc_key_b64:\s*["']([^"']+)["']/i),iv=h.match(/iv_b64:\s*["']([^"']+)["']/i),sm=h.match(/subtitles:\s*["']([^"']*)["']/i);if(!v||!k||!iv)return[];const dec=CryptoJS.AES.decrypt(CryptoJS.lib.CipherParams.create({ciphertext:CryptoJS.enc.Base64.parse(v[1])}),CryptoJS.enc.Base64.parse(k[1]),{iv:CryptoJS.enc.Base64.parse(iv[1]),mode:CryptoJS.mode.CBC,padding:CryptoJS.pad.Pkcs7}).toString(CryptoJS.enc.Utf8).trim();if(!dec)return[];const om=url.match(/^(https?:\/\/[^/]+)/i),ph={"Referer":url,"Origin":om?om[1]:BASE,"User-Agent":UA};let tr=[];if(sm&&sm[1])try{const p=JSON.parse(sm[1].replace(/\\"/g,'"').replace(/\\\//g,"/").replace(/\\u([0-9a-fA-F]{4})/g,(_,x)=>String.fromCharCode(parseInt(x,16))));if(Array.isArray(p))tr=p}catch(_){}const st=subs(tr,ph,String(section).toLowerCase()==="sub"),s=stream(dec,"Zen",section,hard,st,ph,ctx);return s?[s]:[]}
async function servers(ids,types,ctx){const d=await json(`${BASE}/ajax/server/list?servers=${encodeURIComponent(ids)}`,{headers:AJ});if(!d||d.status!==200)return[];const $=cheerio.load(d.result||""),list=[];$("div.server-type").each((_,sec)=>{const n=$(sec),type=String(n.attr("data-type")||"").toLowerCase();if(!types.includes(type))return;const hard=/hard\s*sub/i.test(n.text());n.find("div.server-list > div.server").each((__,el)=>{const id=$(el).attr("data-link-id");if(id)list.push({id,type,hard})})});const all=await Promise.all(list.map(async x=>{const r=await json(`${BASE}/ajax/server?get=${encodeURIComponent(x.id)}`,{headers:AJ}),u=r&&r.result&&r.result.url;if(!u)return[];if(/megaplay\.buzz|rapid-cloud|vidwish\.live/i.test(u))return mega(u,x.type,x.hard,ctx);if(/player\.sgsgsgsr\.site|zencloudz\.cc/i.test(u))return zen(u,x.type,x.hard,ctx);return[]}));const seen=new Set();return all.flat().filter(x=>{const k=x.url+"|"+x.name;if(seen.has(k))return false;seen.add(k);return true})}
async function getStreams(inputId,type="tv",season=1,episode=1){try{type=mediaType(type);const s=type==="movie"?1:(parseInt(season,10)||1),e=type==="movie"?1:(parseFloat(episode)||1),tid=await tmdbId(inputId,type);if(!tid)return[];const t=await tmdbInfo(tid,type);if(!t||!t.title||type==="tv"&&t.genres.length&&!t.genres.includes(16))return[];const map=type==="tv"?await malMap(t.imdb,s,e):null,at=map&&map.mal_id?await aniTitle(map.mal_id):null,titles=uniq([at&&at.english,at&&at.romaji,t.title,t.original]),cand=await search(titles),mal=map&&map.mal_id?+map.mal_id:null,target=map&&map.mal_episode!=null?parseFloat(map.mal_episode):e;let hit=null;for(const c of cand.slice(0,15)){const ep=choose(await episodes(c.url),mal,target);if(ep){hit=ep;break}}if(!hit)return[];const types=[];if(hit.sub)types.push("sub");if(hit.dub)types.push("dub");if(!types.length)return[];const ctx={title:(at&&(at.english||at.romaji))||t.title,s,e},out=await servers(hit.ids,types,ctx);out.sort((a,b)=>Number(/\[DUB\]/i.test(b.name))-Number(/\[DUB\]/i.test(a.name)));return out}catch(err){console.log(`[${NAME}] ${err&&err.message?err.message:err}`);return[]}}
if(typeof module!=="undefined"&&module.exports)module.exports={getStreams};else globalThis.getStreams=getStreams;
